# Generated by Django 3.2.8 on 2021-10-26 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_userip'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='user_ip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_ratings', to='photos.userip'),
            preserve_default=False,
        ),
    ]
